/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Inicio;

import BDclass.BDConexion;
import ClassAngels.MesasClass;
import ClassAngels.PanelRound;
import java.awt.Color;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.PreparedStatement;
import javax.swing.JButton;
import javax.swing.JLabel;

/**
 *
 * @author jluis
 */
public final class MesasSeguimiento extends javax.swing.JFrame {

    int id_mesa;
    int noorden;
    int ordendia;
    String nombreEmpleadoActual;
    private int[] ordenId = new int[20];      // NOORDEN (ID real)
    private int[] ordenDia = new int[20];     // ordendia (visible)
    private String[] empleadosMesa = new String[20];
    Color Mesas = new Color(255, 51, 51);
    private PanelRound[] mesas;
    private JLabel[] etiquetas;

    /**
     * Creates new form Mesas
     */
    public MesasSeguimiento() {

        initComponents();
        setLocationRelativeTo(null);

        // 1️⃣ Inicializar arreglos primero
        mesas = new PanelRound[]{
            Mesa1, Mesa2, Mesa3, Mesa4, Mesa5,
            Mesa6, Mesa7, Mesa8, Mesa9, Mesa10,
            Mesa11, Mesa12, Mesa13, Mesa14, Mesa15,
            Mesa16, Mesa17, Mesa18, Mesa19, Mesa20
        };

        etiquetas = new JLabel[]{
            ME1, ME2, ME3, ME4, ME5,
            ME6, ME7, ME8, ME9, ME10,
            ME11, ME12, ME13, ME14, ME15,
            ME16, ME17, ME18, ME19, ME20
        };

        // 2️⃣ Inicializar arreglo ordenmesa
        for (int i = 0; i < 20; i++) {
            ordenId[i] = 0;
            ordenDia[i] = 0;
            empleadosMesa[i] = "";
        }
        for (int i = 0; i < empleadosMesa.length; i++) {
            empleadosMesa[i] = ""; // sin empleado al inicio
        }

        // 3️⃣ Configurar eventos
        configurarEventos();

        // 4️⃣ Habilitar todo
        habilitartodo();

        // 5️⃣ Consultar disponibilidad real
        disponibilidad(false);

        // 6️⃣ Finalmente actualizar etiquetas
        Etiquetas();
    }

    private void configurarEventos() {

        for (int i = 0; i < mesas.length; i++) {

            int numeroMesa = i; // importante para lambda

            mesas[i].addMouseListener(new java.awt.event.MouseAdapter() {
                @Override
                public void mouseClicked(java.awt.event.MouseEvent evt) {

                    if (mesas[numeroMesa].isEnabled()) {
                        JOptionPane.showMessageDialog(null,
                                "Mesa No Tiene Orden Abierta...");
                    } else {

                        id_mesa = numeroMesa + 1;
                        noorden = ordenId[numeroMesa];
                        MenuSeguimiento F = new MenuSeguimiento(noorden, id_mesa);
                        F.setVisible(true);
                        dispose();
                    }
                }
            });
        }
    }

    public void habilitartodo() {

        for (PanelRound mesa : mesas) {
            mesa.setEnabled(true);
            mesa.setBackground(Color.GREEN);
        }
    }

    public void disponibilidad(boolean estado) {

        ArrayList<MesasClass> result = MesasClass.ListaMesas();

        for (MesasClass mesaObj : result) {

            String nombreMesa = mesaObj.getMesa(); // "MESA1"
            int numeroMesa = Integer.parseInt(nombreMesa.replace("MESA", "")) - 1;

            if (numeroMesa >= 0 && numeroMesa < mesas.length) {

                mesas[numeroMesa].setEnabled(estado);
                mesas[numeroMesa].setBackground(Mesas);

                ordenId[numeroMesa] = mesaObj.getOrden();       // ID real
                ordenDia[numeroMesa] = mesaObj.getOrdendia();   // Visible
                empleadosMesa[numeroMesa] = mesaObj.getNombreEmpleado();
            }
        }
    }

    private void Etiquetas() {

        for (int i = 0; i < etiquetas.length; i++) {

            String ordenTexto;
            String empleadoTexto;

            if (ordenDia[i] == 0) {
                ordenTexto = "Libre";
                empleadoTexto = "";
            } else {
                ordenTexto = String.valueOf(ordenDia[i]);
                empleadoTexto = empleadosMesa[i];
            }

            String texto = "<html><center><body>"
                    + "MESA " + (i + 1)
                    + "<br>Orden No<br>"
                    + "<font color='white'>" + ordenTexto + "</font>"
                    + "<br><font color='yellow'>" + empleadoTexto + "</font>"
                    + "</body></center></html>";

            etiquetas[i].setText(texto);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Mesa1 = new ClassAngels.PanelRound();
        ME1 = new javax.swing.JLabel();
        Mesa2 = new ClassAngels.PanelRound();
        ME2 = new javax.swing.JLabel();
        Mesa3 = new ClassAngels.PanelRound();
        ME3 = new javax.swing.JLabel();
        Mesa4 = new ClassAngels.PanelRound();
        ME4 = new javax.swing.JLabel();
        Mesa5 = new ClassAngels.PanelRound();
        ME5 = new javax.swing.JLabel();
        Mesa6 = new ClassAngels.PanelRound();
        ME6 = new javax.swing.JLabel();
        Mesa7 = new ClassAngels.PanelRound();
        ME7 = new javax.swing.JLabel();
        Mesa8 = new ClassAngels.PanelRound();
        ME8 = new javax.swing.JLabel();
        Mesa9 = new ClassAngels.PanelRound();
        ME9 = new javax.swing.JLabel();
        Mesa10 = new ClassAngels.PanelRound();
        ME10 = new javax.swing.JLabel();
        Mesa11 = new ClassAngels.PanelRound();
        ME11 = new javax.swing.JLabel();
        Mesa12 = new ClassAngels.PanelRound();
        ME12 = new javax.swing.JLabel();
        Mesa13 = new ClassAngels.PanelRound();
        ME13 = new javax.swing.JLabel();
        Mesa14 = new ClassAngels.PanelRound();
        ME14 = new javax.swing.JLabel();
        Mesa15 = new ClassAngels.PanelRound();
        ME15 = new javax.swing.JLabel();
        Mesa16 = new ClassAngels.PanelRound();
        ME16 = new javax.swing.JLabel();
        Mesa17 = new ClassAngels.PanelRound();
        ME17 = new javax.swing.JLabel();
        Mesa18 = new ClassAngels.PanelRound();
        ME18 = new javax.swing.JLabel();
        Mesa19 = new ClassAngels.PanelRound();
        ME19 = new javax.swing.JLabel();
        Mesa20 = new ClassAngels.PanelRound();
        ME20 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        panelRound1 = new ClassAngels.PanelRound();
        jLabel22 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(1060, 643));

        Mesa1.setBackground(new java.awt.Color(255, 153, 153));
        Mesa1.setRoundBottomLeft(20);
        Mesa1.setRoundBottomRight(20);
        Mesa1.setRoundTopLeft(20);
        Mesa1.setRoundTopRight(20);

        ME1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ME1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ME1.setText("MESA 1");

        javax.swing.GroupLayout Mesa1Layout = new javax.swing.GroupLayout(Mesa1);
        Mesa1.setLayout(Mesa1Layout);
        Mesa1Layout.setHorizontalGroup(
            Mesa1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ME1, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );
        Mesa1Layout.setVerticalGroup(
            Mesa1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ME1, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );

        Mesa2.setBackground(new java.awt.Color(255, 153, 153));
        Mesa2.setRoundBottomLeft(20);
        Mesa2.setRoundBottomRight(20);
        Mesa2.setRoundTopLeft(20);
        Mesa2.setRoundTopRight(20);

        ME2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ME2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ME2.setText("MESA 2");

        javax.swing.GroupLayout Mesa2Layout = new javax.swing.GroupLayout(Mesa2);
        Mesa2.setLayout(Mesa2Layout);
        Mesa2Layout.setHorizontalGroup(
            Mesa2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ME2, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );
        Mesa2Layout.setVerticalGroup(
            Mesa2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ME2, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );

        Mesa3.setBackground(new java.awt.Color(255, 153, 153));
        Mesa3.setRoundBottomLeft(20);
        Mesa3.setRoundBottomRight(20);
        Mesa3.setRoundTopLeft(20);
        Mesa3.setRoundTopRight(20);

        ME3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ME3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ME3.setText("MESA 3");

        javax.swing.GroupLayout Mesa3Layout = new javax.swing.GroupLayout(Mesa3);
        Mesa3.setLayout(Mesa3Layout);
        Mesa3Layout.setHorizontalGroup(
            Mesa3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ME3, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );
        Mesa3Layout.setVerticalGroup(
            Mesa3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ME3, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );

        Mesa4.setBackground(new java.awt.Color(255, 153, 153));
        Mesa4.setRoundBottomLeft(20);
        Mesa4.setRoundBottomRight(20);
        Mesa4.setRoundTopLeft(20);
        Mesa4.setRoundTopRight(20);

        ME4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ME4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ME4.setText("MESA 4");

        javax.swing.GroupLayout Mesa4Layout = new javax.swing.GroupLayout(Mesa4);
        Mesa4.setLayout(Mesa4Layout);
        Mesa4Layout.setHorizontalGroup(
            Mesa4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ME4, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );
        Mesa4Layout.setVerticalGroup(
            Mesa4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ME4, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );

        Mesa5.setBackground(new java.awt.Color(255, 153, 153));
        Mesa5.setRoundBottomLeft(20);
        Mesa5.setRoundBottomRight(20);
        Mesa5.setRoundTopLeft(20);
        Mesa5.setRoundTopRight(20);

        ME5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ME5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ME5.setText("MESA 5");

        javax.swing.GroupLayout Mesa5Layout = new javax.swing.GroupLayout(Mesa5);
        Mesa5.setLayout(Mesa5Layout);
        Mesa5Layout.setHorizontalGroup(
            Mesa5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ME5, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );
        Mesa5Layout.setVerticalGroup(
            Mesa5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ME5, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );

        Mesa6.setBackground(new java.awt.Color(255, 153, 153));
        Mesa6.setRoundBottomLeft(20);
        Mesa6.setRoundBottomRight(20);
        Mesa6.setRoundTopLeft(20);
        Mesa6.setRoundTopRight(20);

        ME6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ME6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ME6.setText("MESA 6");

        javax.swing.GroupLayout Mesa6Layout = new javax.swing.GroupLayout(Mesa6);
        Mesa6.setLayout(Mesa6Layout);
        Mesa6Layout.setHorizontalGroup(
            Mesa6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ME6, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );
        Mesa6Layout.setVerticalGroup(
            Mesa6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ME6, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );

        Mesa7.setBackground(new java.awt.Color(255, 153, 153));
        Mesa7.setRoundBottomLeft(20);
        Mesa7.setRoundBottomRight(20);
        Mesa7.setRoundTopLeft(20);
        Mesa7.setRoundTopRight(20);

        ME7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ME7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ME7.setText("MESA 7");

        javax.swing.GroupLayout Mesa7Layout = new javax.swing.GroupLayout(Mesa7);
        Mesa7.setLayout(Mesa7Layout);
        Mesa7Layout.setHorizontalGroup(
            Mesa7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ME7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );
        Mesa7Layout.setVerticalGroup(
            Mesa7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ME7, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );

        Mesa8.setBackground(new java.awt.Color(255, 153, 153));
        Mesa8.setRoundBottomLeft(20);
        Mesa8.setRoundBottomRight(20);
        Mesa8.setRoundTopLeft(20);
        Mesa8.setRoundTopRight(20);

        ME8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ME8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ME8.setText("MESA 8");

        javax.swing.GroupLayout Mesa8Layout = new javax.swing.GroupLayout(Mesa8);
        Mesa8.setLayout(Mesa8Layout);
        Mesa8Layout.setHorizontalGroup(
            Mesa8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ME8, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );
        Mesa8Layout.setVerticalGroup(
            Mesa8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ME8, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );

        Mesa9.setBackground(new java.awt.Color(255, 153, 153));
        Mesa9.setRoundBottomLeft(20);
        Mesa9.setRoundBottomRight(20);
        Mesa9.setRoundTopLeft(20);
        Mesa9.setRoundTopRight(20);

        ME9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ME9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ME9.setText("MESA 9");

        javax.swing.GroupLayout Mesa9Layout = new javax.swing.GroupLayout(Mesa9);
        Mesa9.setLayout(Mesa9Layout);
        Mesa9Layout.setHorizontalGroup(
            Mesa9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ME9, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );
        Mesa9Layout.setVerticalGroup(
            Mesa9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ME9, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );

        Mesa10.setBackground(new java.awt.Color(255, 153, 153));
        Mesa10.setRoundBottomLeft(20);
        Mesa10.setRoundBottomRight(20);
        Mesa10.setRoundTopLeft(20);
        Mesa10.setRoundTopRight(20);

        ME10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ME10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ME10.setText("MESA 10");

        javax.swing.GroupLayout Mesa10Layout = new javax.swing.GroupLayout(Mesa10);
        Mesa10.setLayout(Mesa10Layout);
        Mesa10Layout.setHorizontalGroup(
            Mesa10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ME10, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );
        Mesa10Layout.setVerticalGroup(
            Mesa10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ME10, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );

        Mesa11.setBackground(new java.awt.Color(255, 153, 153));
        Mesa11.setRoundBottomLeft(20);
        Mesa11.setRoundBottomRight(20);
        Mesa11.setRoundTopLeft(20);
        Mesa11.setRoundTopRight(20);

        ME11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ME11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ME11.setText("MESA 11");

        javax.swing.GroupLayout Mesa11Layout = new javax.swing.GroupLayout(Mesa11);
        Mesa11.setLayout(Mesa11Layout);
        Mesa11Layout.setHorizontalGroup(
            Mesa11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ME11, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );
        Mesa11Layout.setVerticalGroup(
            Mesa11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ME11, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );

        Mesa12.setBackground(new java.awt.Color(255, 153, 153));
        Mesa12.setRoundBottomLeft(20);
        Mesa12.setRoundBottomRight(20);
        Mesa12.setRoundTopLeft(20);
        Mesa12.setRoundTopRight(20);

        ME12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ME12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ME12.setText("MESA 12");

        javax.swing.GroupLayout Mesa12Layout = new javax.swing.GroupLayout(Mesa12);
        Mesa12.setLayout(Mesa12Layout);
        Mesa12Layout.setHorizontalGroup(
            Mesa12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ME12, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );
        Mesa12Layout.setVerticalGroup(
            Mesa12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ME12, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );

        Mesa13.setBackground(new java.awt.Color(255, 153, 153));
        Mesa13.setRoundBottomLeft(20);
        Mesa13.setRoundBottomRight(20);
        Mesa13.setRoundTopLeft(20);
        Mesa13.setRoundTopRight(20);

        ME13.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ME13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ME13.setText("MESA 13");

        javax.swing.GroupLayout Mesa13Layout = new javax.swing.GroupLayout(Mesa13);
        Mesa13.setLayout(Mesa13Layout);
        Mesa13Layout.setHorizontalGroup(
            Mesa13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ME13, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );
        Mesa13Layout.setVerticalGroup(
            Mesa13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ME13, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );

        Mesa14.setBackground(new java.awt.Color(255, 153, 153));
        Mesa14.setRoundBottomLeft(20);
        Mesa14.setRoundBottomRight(20);
        Mesa14.setRoundTopLeft(20);
        Mesa14.setRoundTopRight(20);

        ME14.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ME14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ME14.setText("MESA 14");

        javax.swing.GroupLayout Mesa14Layout = new javax.swing.GroupLayout(Mesa14);
        Mesa14.setLayout(Mesa14Layout);
        Mesa14Layout.setHorizontalGroup(
            Mesa14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ME14, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );
        Mesa14Layout.setVerticalGroup(
            Mesa14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ME14, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );

        Mesa15.setBackground(new java.awt.Color(255, 153, 153));
        Mesa15.setRoundBottomLeft(20);
        Mesa15.setRoundBottomRight(20);
        Mesa15.setRoundTopLeft(20);
        Mesa15.setRoundTopRight(20);

        ME15.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ME15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ME15.setText("MESA 15");

        javax.swing.GroupLayout Mesa15Layout = new javax.swing.GroupLayout(Mesa15);
        Mesa15.setLayout(Mesa15Layout);
        Mesa15Layout.setHorizontalGroup(
            Mesa15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ME15, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );
        Mesa15Layout.setVerticalGroup(
            Mesa15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ME15, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );

        Mesa16.setBackground(new java.awt.Color(255, 153, 153));
        Mesa16.setRoundBottomLeft(20);
        Mesa16.setRoundBottomRight(20);
        Mesa16.setRoundTopLeft(20);
        Mesa16.setRoundTopRight(20);

        ME16.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ME16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ME16.setText("MESA 16");

        javax.swing.GroupLayout Mesa16Layout = new javax.swing.GroupLayout(Mesa16);
        Mesa16.setLayout(Mesa16Layout);
        Mesa16Layout.setHorizontalGroup(
            Mesa16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ME16, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );
        Mesa16Layout.setVerticalGroup(
            Mesa16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ME16, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );

        Mesa17.setBackground(new java.awt.Color(255, 153, 153));
        Mesa17.setRoundBottomLeft(20);
        Mesa17.setRoundBottomRight(20);
        Mesa17.setRoundTopLeft(20);
        Mesa17.setRoundTopRight(20);

        ME17.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ME17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ME17.setText("MESA 17");

        javax.swing.GroupLayout Mesa17Layout = new javax.swing.GroupLayout(Mesa17);
        Mesa17.setLayout(Mesa17Layout);
        Mesa17Layout.setHorizontalGroup(
            Mesa17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ME17, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );
        Mesa17Layout.setVerticalGroup(
            Mesa17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ME17, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );

        Mesa18.setBackground(new java.awt.Color(255, 153, 153));
        Mesa18.setRoundBottomLeft(20);
        Mesa18.setRoundBottomRight(20);
        Mesa18.setRoundTopLeft(20);
        Mesa18.setRoundTopRight(20);

        ME18.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ME18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ME18.setText("MESA 18");

        javax.swing.GroupLayout Mesa18Layout = new javax.swing.GroupLayout(Mesa18);
        Mesa18.setLayout(Mesa18Layout);
        Mesa18Layout.setHorizontalGroup(
            Mesa18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ME18, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );
        Mesa18Layout.setVerticalGroup(
            Mesa18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ME18, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );

        Mesa19.setBackground(new java.awt.Color(255, 153, 153));
        Mesa19.setRoundBottomLeft(20);
        Mesa19.setRoundBottomRight(20);
        Mesa19.setRoundTopLeft(20);
        Mesa19.setRoundTopRight(20);

        ME19.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ME19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ME19.setText("MESA 19");

        javax.swing.GroupLayout Mesa19Layout = new javax.swing.GroupLayout(Mesa19);
        Mesa19.setLayout(Mesa19Layout);
        Mesa19Layout.setHorizontalGroup(
            Mesa19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ME19, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );
        Mesa19Layout.setVerticalGroup(
            Mesa19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ME19, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );

        Mesa20.setBackground(new java.awt.Color(255, 153, 153));
        Mesa20.setRoundBottomLeft(20);
        Mesa20.setRoundBottomRight(20);
        Mesa20.setRoundTopLeft(20);
        Mesa20.setRoundTopRight(20);

        ME20.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ME20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ME20.setText("MESA 20");

        javax.swing.GroupLayout Mesa20Layout = new javax.swing.GroupLayout(Mesa20);
        Mesa20.setLayout(Mesa20Layout);
        Mesa20Layout.setHorizontalGroup(
            Mesa20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ME20, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );
        Mesa20Layout.setVerticalGroup(
            Mesa20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Mesa20Layout.createSequentialGroup()
                .addComponent(ME20, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("CONTROL");

        panelRound1.setBackground(new java.awt.Color(255, 255, 0));
        panelRound1.setRoundBottomLeft(20);
        panelRound1.setRoundBottomRight(20);
        panelRound1.setRoundTopLeft(20);
        panelRound1.setRoundTopRight(20);

        jLabel22.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22.setText("INICIO");
        jLabel22.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel22MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelRound1Layout = new javax.swing.GroupLayout(panelRound1);
        panelRound1.setLayout(panelRound1Layout);
        panelRound1Layout.setHorizontalGroup(
            panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel22, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );
        panelRound1Layout.setVerticalGroup(
            panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel22, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(106, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 861, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Mesa15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Mesa8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Mesa1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Mesa2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Mesa9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Mesa16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(39, 39, 39)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(Mesa17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Mesa18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(Mesa10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Mesa11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(Mesa3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(29, 29, 29)
                                .addComponent(Mesa4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Mesa5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Mesa12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Mesa19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(Mesa6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(Mesa7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(Mesa13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(Mesa14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(Mesa20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(panelRound1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(93, 93, 93))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Mesa7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Mesa6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Mesa5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Mesa4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Mesa3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Mesa2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Mesa1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Mesa8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Mesa9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Mesa10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Mesa11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Mesa12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Mesa13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Mesa14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Mesa15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Mesa16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Mesa17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Mesa18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Mesa19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Mesa20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelRound1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(203, 203, 203))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel22MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel22MouseClicked
        Ordenes F = new Ordenes();
        F.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel22MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MesasSeguimiento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MesasSeguimiento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MesasSeguimiento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MesasSeguimiento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MesasSeguimiento().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ME1;
    private javax.swing.JLabel ME10;
    private javax.swing.JLabel ME11;
    private javax.swing.JLabel ME12;
    private javax.swing.JLabel ME13;
    private javax.swing.JLabel ME14;
    private javax.swing.JLabel ME15;
    private javax.swing.JLabel ME16;
    private javax.swing.JLabel ME17;
    private javax.swing.JLabel ME18;
    private javax.swing.JLabel ME19;
    private javax.swing.JLabel ME2;
    private javax.swing.JLabel ME20;
    private javax.swing.JLabel ME3;
    private javax.swing.JLabel ME4;
    private javax.swing.JLabel ME5;
    private javax.swing.JLabel ME6;
    private javax.swing.JLabel ME7;
    private javax.swing.JLabel ME8;
    private javax.swing.JLabel ME9;
    private ClassAngels.PanelRound Mesa1;
    private ClassAngels.PanelRound Mesa10;
    private ClassAngels.PanelRound Mesa11;
    private ClassAngels.PanelRound Mesa12;
    private ClassAngels.PanelRound Mesa13;
    private ClassAngels.PanelRound Mesa14;
    private ClassAngels.PanelRound Mesa15;
    private ClassAngels.PanelRound Mesa16;
    private ClassAngels.PanelRound Mesa17;
    private ClassAngels.PanelRound Mesa18;
    private ClassAngels.PanelRound Mesa19;
    private ClassAngels.PanelRound Mesa2;
    private ClassAngels.PanelRound Mesa20;
    private ClassAngels.PanelRound Mesa3;
    private ClassAngels.PanelRound Mesa4;
    private ClassAngels.PanelRound Mesa5;
    private ClassAngels.PanelRound Mesa6;
    private ClassAngels.PanelRound Mesa7;
    private ClassAngels.PanelRound Mesa8;
    private ClassAngels.PanelRound Mesa9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JPanel jPanel1;
    private ClassAngels.PanelRound panelRound1;
    // End of variables declaration//GEN-END:variables

}
