/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Inicio;

import BDclass.BDConexion;
import ClassAngels.OrdenPendiente;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.GridLayout;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.util.ArrayList;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JButton;
import javax.swing.JFrame;

/**
 *
 * @author it
 */
public class OrdenesSinMesa extends javax.swing.JFrame {

    /**
     * Creates new form OrdenesSinMesa
     */
    public OrdenesSinMesa() {
        initComponents();
        setLocationRelativeTo(null);
        configurarPanel();
        cargarBotonesOrdenes();

        setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);

        addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
                volverAOrdenes();
            }
        });
    }

    private void configurarPanel() {

        panelOrdenes.setLayout(new FlowLayout());
        // 3 columnas, filas automáticas
    }

    private void cargarBotonesOrdenes() {

        panelOrdenes.removeAll();

        ArrayList<OrdenPendiente> lista = listaOrdenesSinMesa();

        for (OrdenPendiente o : lista) {

            JButton boton = new JButton(
                    "<html><div style='text-align:center;'>"
                    + "<b><font size='4'>NO. ORDEN " + o.getOrdendia() + "</font></b>"
                    + "<br><br>"
                    + "<font color='green'><b>TOTAL: Q" + String.format("%.2f", o.getTotal()) + "</b></font>"
                    + "<br><br>"
                    + "<font color='blue'>" + o.getEmpleado() + "</font>"
                    + "</div></html>"
            );

            boton.setPreferredSize(new Dimension(200, 120));
            boton.setFocusPainted(false);

            int noorden = o.getNoorden();

            boton.addActionListener(e -> {
                MenuSeguimiento F = new MenuSeguimiento(noorden, 0);
                F.setVisible(true);
                dispose();
            });

            panelOrdenes.add(boton);
        }

        panelOrdenes.revalidate();
        panelOrdenes.repaint();
    }

    private void volverAOrdenes() {
        Ordenes F = new Ordenes();
        F.setVisible(true);
        dispose();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelOrdenes = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout panelOrdenesLayout = new javax.swing.GroupLayout(panelOrdenes);
        panelOrdenes.setLayout(panelOrdenesLayout);
        panelOrdenesLayout.setHorizontalGroup(
            panelOrdenesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1134, Short.MAX_VALUE)
        );
        panelOrdenesLayout.setVerticalGroup(
            panelOrdenesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 636, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelOrdenes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelOrdenes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OrdenesSinMesa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OrdenesSinMesa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OrdenesSinMesa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OrdenesSinMesa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OrdenesSinMesa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel panelOrdenes;
    // End of variables declaration//GEN-END:variables

    public static ArrayList<OrdenPendiente> listaOrdenesSinMesa() {

        ArrayList<OrdenPendiente> lista = new ArrayList<>();
        BDConexion conecta = new BDConexion();
        Connection cn = conecta.getConexion();

        String sql = "select noorden,ordendia,total,NOMBRE_corto "
                + "from ordenes o "
                + "inner join empleados e on o.CODIGOEMPLEADO = e.CODIGO "
                + "where ID_MESA IS NULL "
                + "and date(fecha) = curdate() and o.estado = 1";

        try {
            Statement st = cn.createStatement();
            ResultSet rs = st.executeQuery(sql);

            while (rs.next()) {
                OrdenPendiente o = new OrdenPendiente();
                o.setNoorden(rs.getInt("noorden"));
                o.setOrdendia(rs.getInt("ordendia"));
                o.setTotal(rs.getDouble("total"));
                o.setEmpleado(rs.getString("NOMBRE_corto"));
                lista.add(o);
            }

            cn.close();

        } catch (Exception e) {
            System.out.println("Error: " + e);
        }

        return lista;
    }

}
